### ISSUE TITLE
Survey of Model A (ASR/STT)

### ISSUE THREAD

**Issue by wkCircle** [Cockatoo-AI-Org/Cockatoo.AI#6]
Survey of Model A for Automatic Speech Recognition, or the so called Speech to Text. 
Also survey which library is appropriate to manage the model. 
When the survey is done, please feel free to update README.md or upload files to conclude your results.

**Comment by wkCircle** [comment]
When the survey is done, you may update README.md or upload files to conclude your results.

**Comment by johnklee** [comment]
First step is too collect candidates of ASR/STT and start research on them:
* [ ] [Easy Speech-to-Text with Python](https://towardsdatascience.com/easy-speech-to-text-with-python-3df0d973b426)

**Comment by johnklee** [comment]
Per discussion on group meeting 1/8, I will start to collect audio files and use them to evaluate the STT models as candidates. On the other hand, I will start coding to build up a utility to do the evaluation automatically and produce performance report as well.

**Comment by johnklee** [comment]
Hi @wkCircle ,

If no extra model A for me to look into or survey from, I will close this issue and move my focus to another issue https://github.com/Cockatoo-AI-Org/Cockatoo.AI/issues/30

We could still open another issue to do survey of model A if anyone has any input or suggestion. Any advice is appreciated.

**Comment by wkCircle** [comment]
Agree, thanks for your input!

**Comment by johnklee** [comment]
Closed this issue for no more model A to work on. Thanks!
